### PR TITLE
Update game workflow to end at arbitray number of capture pieces (4) …

### PR DESCRIPTION
**Pull request by lowellmower**
…and make moves possible

### CODE REVIEW

**Comment by lowellmower** [comment]
@grapefruitricky @gechro @julia-castro move method is implemented on the game controller. All the logic works however, the display of the board shifts weird after a piece is moved - - if anyone can fix the to_s to keep it consistent that would be awesome.

**Comment by lowellmower** [comment]
The game is also set to end at an arbitrary number of captured pieces currently set to 4

**Comment by arosswilson** [comment]
@lowellmower @gechro @julia-castro 

I can take a look at it in an hour - I'm trying to finish my todo list first

**Comment by lowellmower** [comment]
@grapefruitricky no worries if you don't get to it... the pieces 'move' currently, just have room for improvement. We at least have an MVP

**Pull request merged**
