### PR TITLE
Gechro/setup game

### PR DESCRIPTION
**Pull request by gechro**
@lowellmower  ... not sure if im crossing the single responsibility thing... as far as the players go

### CODE REVIEW

**Comment by gechro** [comment]
added HASH for convert coordinate

**Comment by gechro** [comment]
@lowellmower

**Comment by lowellmower** [comment]
@gechro we have all this on the 'bishop' branch, correct? Am I good to delete this branch?

**Comment by gechro** [comment]
Yes :) @lowellmower

**Pull request closed without merging**
